app/ClasseApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core.views import *
from api.urls import router

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path(
        "insegnanti/",
        include(("insegnanti.urls", "insegnanti"), namespace="insegnanti"),
    ),
    path("genitori/", include(("genitori.urls", "genitori"), namespace="genitori")),
    # path("api/", include(router.urls)),
    # path('accounts/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

app/api/urls.py
from django.urls import path, include
from rest_framework import routers
from .viewsets import *

router = routers.DefaultRouter()
router.register("evento", EventoViewSet)
router.register("compito", CompitoViewSet)
router.register("classe", ClasseViewSet)
router.register("alunno", AlunnoViewSet)
router.register("genitore", GenitoreViewSet)
router.register("insegnante", InsegnanteViewSet)
router.register("user", UserViewSet)
# router.register(r'users', UserViewSet)
urlpatterns = router.urls

urlpatterns += [path("rest-auth/", include("rest_auth.urls"))]

app/insegnanti/urls.py
from django.urls import path
from .views import (
    SignupInsegnante,
    LoginInsegnante,
    ClasseCreate,
    ajax_mostra_compito_form,
    AggiungiCompito,
    ClasseAggiungiInsegnante,
)
from core.views import home_view

urlpatterns = [
    path("signup/insegnante/", SignupInsegnante.as_view(), name="signup-insegnante"),
    path("login/insegnante/", LoginInsegnante.as_view(), name="login-insegnante"),
    path("home/insegnante/", home_view, name="home-insegnante"),
    path("classe/create", ClasseCreate.as_view(), name="aggiungi-classe"),
    path(
        "insegnante/classe/<int:classe_pk>/aggiungi-compito/",
        AggiungiCompito.as_view(),
        name="aggiungi-compito",
    ),
    path(
        "classe/<uuid:uuid>/conferma-insegnante",
        ClasseAggiungiInsegnante.as_view(),
        name="classe_aggiungi_insegnante",
    ),
    path(
        "ajax/forms/classe/<int:classe_pk>/aggiungicompito/",
        ajax_mostra_compito_form,
        name="ajax-compito-form",
    ),
]

app/insegnanti/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction

from core.models import *


class InsegnanteForm(forms.ModelForm):
    class Meta:
        model = Insegnante
        exclude = ["user", "scuola"]


class ClasseForm(forms.ModelForm):
    class Meta:
        model = Classe
        exclude = ["scuola"]


class CompitoForm(forms.ModelForm):
    data = forms.DateField(
        input_formats=["%d/%m/%Y"],
        widget=forms.DateInput(
            attrs={
                "class": "form-control datetimepicker-input",
                "data-target": "#data-compito-picker",
            }
        ),
    )

    class Meta:
        model = Compito
        exclude = ["classe", "creatore"]

app/insegnanti/views.py
from django.utils.decorators import method_decorator
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth import views as auth_views, authenticate, login
from django.views.generic import FormView, TemplateView, DetailView, CreateView
from django import views
from django.utils import timezone
from django.urls import reverse_lazy, reverse

from .forms import *
from core.forms import CustomUserCreationForm, AuthenticationFormInsegnante
from core.models import Insegnante, Classe

LOGIN_URL_INSEGNANTE = reverse_lazy("insegnanti:login-insegnante")

# Create your views here.


class InsegnanteRequiredMixin(LoginRequiredMixin, UserPassesTestMixin):
    """ Classe da comporre (aggiungere in testa alla lista di classi di 
        eredita') per ottenere una View che autorizza solo gli insegnanti 
        autenticati.
    """

    login_url = LOGIN_URL_INSEGNANTE

    def test_func(self):
        return hasattr(self.request.user, "insegnante")


def insegnante_required(view):
    def newview(request, *args, **kwargs):
        if not hasattr(request.user, "insegnante"):
            raise PermissionDenied
        return view(request, *args, **kwargs)

    return newview


class SignupInsegnante(FormView):
    form_class = CustomUserCreationForm
    template_name = "insegnanti/signup_insegnante.html"

    def form_valid(self, form):
        with transaction.atomic():
            self.object = form.save()
            insegnante = Insegnante.objects.create(user=self.object)
            insegnante.save()
        return redirect(LOGIN_URL_INSEGNANTE)


class LoginInsegnante(views.View):
    errors = None

    def __init__(self, *args, **kwargs):
        super(LoginInsegnante, self).__init__(*args, **kwargs)
        if "errors" in kwargs:
            self.errors = kwargs["errors"]

    def get(self, request):
        form = AuthenticationFormInsegnante()
        return render(
            request,
            "insegnanti/login_insegnante.html",
            {"form": form, "errors": self.errors},
        )

    def post(self, request):
        form = AuthenticationFormInsegnante(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("insegnanti:home-insegnante")
        return render(request, "insegnanti/login_insegnante.html", {"form": form})


class ClasseCreate(InsegnanteRequiredMixin, CreateView):
    model = Classe
    fields = ["anno", "sezione", "anno_inizio"]
    template_name = "core/classe_create.html"

    def form_valid(self, form):
        form.instance.insegnanti.add(request.user.insegnante)
        self.object = form.save()
        return super(CreateView, self).form_valid(form)


@insegnante_required
@login_required
def ajax_mostra_compito_form(request, classe_pk):
    if not request.is_ajax():
        raise PermissionDenied
    if request.method == "GET":
        classe = Classe.objects.get(pk=classe_pk)
        form = CompitoForm()
        return render(
            request,
            "insegnanti/compito_form.html",
            {"form": form, "classe_pk": classe_pk, "classe": classe},
        )


class AggiungiCompito(InsegnanteRequiredMixin, CreateView):
    model = Compito
    form_class = CompitoForm
    template_name = "insegnanti/aggiungi_compito.html"

    def form_valid(self, form):
        context = self.get_context_data()
        classe_pk, classe = context["classe_pk"], context["classe"]
        compito = form.save(commit=False)
        compito.classe = classe
        compito.creatore = self.request.user.insegnante
        compito.save()
        return redirect(reverse("dettagli-classe", kwargs={"pk": classe_pk}))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        classe_pk = self.kwargs.get("classe_pk")
        context["classe_pk"] = classe_pk
        context["classe"] = get_object_or_404(Classe, pk=classe_pk)
        self.context = context
        return context


class ClasseAggiungiInsegnante(InsegnanteRequiredMixin, views.View):
    def post(self, request, uuid):
        classe = get_object_or_404(Classe, uuid=uuid)
        classe.insegnanti.add(request.user.insegnante)
        return redirect(reverse("dettagli-classe", kwargs={"pk": classe.pk}))

    def get(self, request, uuid):
        classe = get_object_or_404(Classe, uuid=uuid)
        return render(
            request,
            "insegnanti/conferma_invito.html",
            context={"classe": classe, "classe_uuid": str(classe.uuid)},
        )

app/insegnanti/templates/insegnanti/aggiungi_compito.html
<!-- vim: syntax=htmldjango
-->
{% extends 'core/base.html' %}

{% block content %}
<div class='row'>
    <div class='col'>
        {% include 'insegnanti/compito_form.html' %}
    </div>
</div>
{% endblock content %}

app/insegnanti/templates/insegnanti/classe_dettagli.html
<!--
    vim: syntax=htmldjango
-->
{% extends 'insegnanti/home_insegnante.html' %}

{% block insegnante_content %}
<div class='row'>
    <div class='col'>
        {% include "core/classe_titolo.html" %}
    </div>
</div>

<div id='compito-form' class='row'>
</div>

<script>
    $('#aggiungi-compito').click( function(e) {
        $.ajax({
            url: '{% url "insegnanti:ajax-compito-form" classe.pk %}',
            success: function(data) {
                $('#compito-form').html(data);
            }
        })   
    })
</script>

{% include "core/compiti_lista.html" %}


{% endblock insegnante_content %}

app/insegnanti/templates/insegnanti/compito_form.html
<!-- vim: syntax=htmldjango
-->
{% load crispy_forms_tags %}
<div class='col-8'>
    <h5> Aggiungi compiti per la classe {{classe}} </h5>
    <form 
        method='post' 
        enctype='multipart/form-data'
        action='{% url "insegnanti:aggiungi-compito" classe_pk %}' 
        autocomplete='off'>
            {{form|crispy}}
            {% csrf_token %}
        </table>
        <input type='submit' class='btn btn-primary' value='Aggiungi' />
    <script>
        $( function() { 
            // add calendar widget
            $('[data-target="#data-compito-picker"]').datepicker({
                dateFormat: "dd/mm/yy",
                changeMonth: true,
                changeYear: true
            }); 
            // prevent autocompletion
            $('[data-target="#data-compito-picker"]')
                .attr('autocomplete','off'); 
        } );
    </script>
    </form>
</div>

app/insegnanti/templates/insegnanti/conferma_invito.html
{% extends 'core/base.html' %}

{% block content %}
{% load crispy_forms_tags %}

<div class='row'>
    <div class='col'>
        <h1> Benvenuto {{user.full_name}} </h1>
        <h3> 
            Sembra che tu sia stato invitato a far parte del gruppo della {{classe}} 
        </h3>
        <p> Se vuoi unirti a questa classe, usa il pulsante qui sotto. </p>
        <div style='padding:1pt'>
            <form 
                method=post
                action="#">
                {% csrf_token %}
                <button type=Submit class='btn btn-primary btn-large'>
                    Sono un'insegnante di questa classe
                </button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

app/insegnanti/templates/insegnanti/home_insegnante.html
<!--
    vim: syntax=htmldjango
-->
{% extends "core/base.html" %}

{% block content %}

<div class='row'>
	<h1> Ciao {{ user.full_name }} </h1>
</div>
<hr/>

{% block insegnante_content %}
	{% include "insegnanti/pannello_classi.html" %}
{% endblock insegnante_content %}

{% endblock content %}

app/insegnanti/templates/insegnanti/login_insegnante.html
<!-- 
    vim: syntax=htmldjango  
-->
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class='row'>
    <h1> Accedi come insegnante </h1>
</div>
<hr />
<div class='row'>
    <form method='post' action="{% url 'insegnanti:login-insegnante' %}">
            {% csrf_token %}
            {{ form|crispy }}
        <input type='submit' class='btn btn-primary' value='Accedi' />
    </form>
</div>
{% endblock content %}

app/insegnanti/templates/insegnanti/pannello_classi.html
<!--
    vim: syntax=htmldjango
-->

<div class='row'>
    <div class='col-8'>
        <h1> Classi </h1>
    </div>
    <div class='col-4'>
		<p> <button class='btn btn-primary' id='unisciti-classe'>
			Unisciti ad una classe
		</button> </p>
    </div>
</div>

<div style='display:none' id='cerca-classe-form' class='row'>
    {% include "core/form_invito_classe.html" %} 
</div>

<script>
    $('#unisciti-classe').click( function(e) {
        $('#cerca-classe-form').slideDown();
    });
</script>

{% if user.insegnante.classi.exists %}
    {% for classe in user.insegnante.classi.all %}
        <div class='row'>
            <div class='col'>
				<h3>
                    <a href='{% url "dettagli-classe" classe.pk %}'>
					    {{ classe }}
			        </a> 
                </h3>
            </div>
        </div>
        <hr />
    {% endfor %}
{% else %}
	<p> Non ti sei ancora unito ad alcuna classe. </p>
{% endif %}

app/insegnanti/templates/insegnanti/signup_insegnante.html
{% extends "core/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<div class='row' >
    <div class='col-6' >
        <h1> Registrazione insegnante </h1>
    </div>
</div>
<div class='row' >
    <div class='col-6' >
        <form method=POST action='{% url "insegnanti:signup-insegnante" %}'>
				{% csrf_token %}
                {{ form|crispy }} 
            <input type='submit' value='submit' class='btn btn-primary' />
        </form>
    </div>
</div>

    <script>
        $( function() { 
            $('[data-target="#data-nascita-picker"]').datepicker({
                yearRange: '1920:2019',
                changeMonth: true,
                changeYear: true
            }); 
            $('[data-target="#data-nascita-picker"]').attr('autocomplete','off'); 
        } );
    </script>
{% endblock content %}