app/ClasseApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core.views import *
from api.urls import router

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path(
        "insegnanti/",
        include(("insegnanti.urls", "insegnanti"), namespace="insegnanti"),
    ),
    path("genitori/", include(("genitori.urls", "genitori"), namespace="genitori")),
    # path("api/", include(router.urls)),
    # path('accounts/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

app/api/urls.py
from django.urls import path, include
from rest_framework import routers
from .viewsets import *

router = routers.DefaultRouter()
router.register("evento", EventoViewSet)
router.register("compito", CompitoViewSet)
router.register("classe", ClasseViewSet)
router.register("alunno", AlunnoViewSet)
router.register("genitore", GenitoreViewSet)
router.register("insegnante", InsegnanteViewSet)
router.register("user", UserViewSet)
# router.register(r'users', UserViewSet)
urlpatterns = router.urls

urlpatterns += [path("rest-auth/", include("rest_auth.urls"))]

app/genitori/urls.py
from django.urls import path
from .views import *
from core.views import home_view

urlpatterns = [
    path("signup/genitore/", SignupGenitore.as_view(), name="signup-genitore"),
    path("login/genitore/", LoginGenitore.as_view(), name="login-genitore"),
    path("profile/genitore/", home_view, name="home-genitore"),
    path("classe/create", ClasseCreate.as_view(), name="aggiungi-classe"),
    path("classe/<int:pk>/delete", ClasseDelete.as_view(), name="classe-delete"),
    path(
        "classe/<uuid:uuid>/conferma-genitore",
        ClasseAggiungiGenitore.as_view(),
        name="classe_aggiungi_genitore",
    ),
    path(
        "classe/<int:pk>/modifica_rappresentanti",
        ModificaRappresentanti.as_view(),
        name="modifica_rappresentanti",
    ),
    # eventi
    path(
        "genitore/classe/<int:classe_pk>/aggiungi-evento",
        EventoCreate.as_view(),
        name="aggiungi-evento",
    ),
    path("evento/<int:pk>/", EventoDetail.as_view(), name="dettagli-evento"),
    path("evento/<int:pk>/update", EventoUpdate.as_view(), name="evento-update"),
    # inviti a eventi
    path(
        "evento/<int:pk>/inviti_edit",
        EventoInvitoUpdate.as_view(template_name="genitori/evento_invito_form.html"),
        name="aggiungi-invito-evento",
    ),
    path(
        "invito_evento/<int:pk>/<str:accetta>/",
        ajax_accetta_rifiuta_invito_evento,
        name="conferma-invito-evento",
    ),
    # collette
    # path("colletta/create", CollettaCreate.as_view(), name="colletta-create"),
    path(
        "evento/<int:evento_pk>/colletta/create",
        CollettaAssociate.as_view(),
        name="colletta-evento-associa",
    ),
    path(
        "evento/<int:pk>/colletta/update",
        CollettaUpdate.as_view(),
        name="colletta-update",
    ),
    # path("colletta/<int:pk>", CollettaDetail.as_view(), name="colletta-detail"),
    path(
        "invito_colletta/<int:pk>/<str:accetta>/",
        ajax_accetta_rifiuta_invito_colletta,
        name="conferma-invito-colletta",
    ),
]

app/genitori/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.forms.models import inlineformset_factory

from core.models import *


class GenitoreForm(forms.ModelForm):
    class Meta:
        model = Genitore
        exclude = ["user", "figli"]


class AlunnoForm(forms.ModelForm):
    # classe = forms.UUIDField(label="Codice invito classe")

    # def clean_classe(self):
    #     """ Controlla che l'uuid della classe esista """
    #     uuid = self.cleaned_data["classe"]
    #     try:
    #         classe = Classe.objects.get(uuid=uuid)
    #     except Classe.DoesNotExist:
    #         raise ValidationError("Codice classe non esistente")

    class Meta:
        model = Alunno
        exclude = ["genitore"]
        help_texts = {
            "classe": "Il codice di invito e' una sequenza di caratteri "
            + "utilizzata per accedere a una classe. Se non ne sei "
            + "in possesso, chiedi al tuo rappresentante di classe."
        }


class EventoForm(forms.ModelForm):
    class Meta:
        model = Evento
        exclude = ["classe", "creatore"]


ClasseAlunnoFormset = forms.inlineformset_factory(
    Classe, Alunno, form=AlunnoForm, extra=1, can_delete=False
)


class SceltaFiglioForm(forms.Form):

    figlio = forms.ModelChoiceField(queryset=None, required=False)

    def __init__(self, *args, **kwargs):
        genitore = kwargs.pop("genitore")
        super(SceltaFiglioForm, self).__init__(*args, **kwargs)
        self.fields["figlio"].queryset = genitore.figli.all()


class RicercaClasseForm(forms.Form):
    classe = forms.UUIDField(label="Codice invito classe")

app/genitori/views.py
from django.db import transaction
from django.forms import modelform_factory
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse, Http404, JsonResponse
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth import views as auth_views, authenticate, login
from django.views.generic import *
from django import views
from itertools import zip_longest

from django.utils import timezone

from .forms import *
from core.forms import CustomUserCreationForm, AuthenticationFormGenitore
from core.models import *
from core.views import is_genitore

LOGIN_URL_GENITORE = reverse_lazy("genitori:login-genitore")
# Create your views here.


class GenitoreRequiredMixin(LoginRequiredMixin, UserPassesTestMixin):
    """ Classe da comporre (aggiungere in testa alla lista di classi di 
        eredita') per ottenere una View che autorizza solo i genitori 
        autenticati.
    """

    login_url = LOGIN_URL_GENITORE

    def test_func(self):
        return hasattr(self.request.user, "genitore")


class AjaxableResponseMixin:
    """
    Mixin to add AJAX support to a form.
    Must be used with an object-based FormView (e.g. CreateView)
    """

    def form_invalid(self, form):
        response = super().form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):
        # We make sure to call the parent's form_valid() method because
        # it might do some processing (in the case of CreateView, it will
        # call form.save() for example).
        response = super().form_valid(form)
        if self.request.is_ajax():
            data = {"pk": self.object.pk}
            return JsonResponse(data)
        else:
            return response


def genitore_required(view):
    def wrapper(request, *args, **kwargs):
        if not is_genitore(request.user):
            raise PermissionDenied
        return view(request, *args, **kwargs)

    return wrapper


def ajax_required(view):
    def wrapper(request, *args, **kwargs):
        if not request.is_ajax():
            raise PermissionDenied
        return view(request, *args, **kwargs)

    return wrapper


class SignupGenitore(CreateView):
    form_class = CustomUserCreationForm
    template_name = "genitori/signup_genitore.html"

    def form_valid(self, form):
        with transaction.atomic():
            self.object = form.save()
            genitore = Genitore.objects.create(user=self.object)
            genitore.save()
        return redirect(LOGIN_URL_GENITORE)


class LoginGenitore(views.View):
    def get(self, request):
        form = AuthenticationFormGenitore()
        return render(request, "genitori/login_genitore.html", {"form": form})

    def post(self, request):
        form = AuthenticationFormGenitore(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("genitori:home-genitore")
        return render(request, "genitori/login_genitore.html", {"form": form})


class ClasseCreate(GenitoreRequiredMixin, CreateView):
    model = Classe
    fields = ["anno", "sezione", "anno_inizio"]
    template_name = "genitori/classe_create.html"

    def get_context_data(self, **kwargs):
        data = super(ClasseCreate, self).get_context_data(**kwargs)
        genitore = self.request.user.genitore
        if self.request.POST:
            data["scelta_figlio"] = SceltaFiglioForm(
                self.request.POST, genitore=genitore
            )
            data["form_alunni"] = ClasseAlunnoFormset(self.request.POST)
        else:
            form = data["form"]
            data["scelta_figlio"] = SceltaFiglioForm(genitore=genitore)
            data["form_alunni"] = ClasseAlunnoFormset()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        form_alunni = context["form_alunni"]
        scelta_figlio = context["scelta_figlio"]
        genitore = self.request.user.genitore
        with transaction.atomic():
            classe = form.save()
            classe.rappresentanti.add(genitore)
            classe.save()
            self.object = classe
            if scelta_figlio.is_valid() and scelta_figlio.cleaned_data["figlio"]:
                alunno = scelta_figlio.cleaned_data["figlio"]
                alunno.classe = self.object
                alunno.save()
            elif form_alunni.is_valid():
                alunni = form_alunni.save(commit=False)
                for alunno in alunni:
                    alunno.genitore = genitore
                    alunno.classe = self.object
                    alunno.save()
            classe.save()
        return super(ClasseCreate, self).form_valid(form)


class ClasseDelete(GenitoreRequiredMixin, DeleteView):
    model = Classe
    template_name = "genitori/classe_delete.html"
    success_url = "/"

    def get_object(self, queryset=None):
        classe = super(ClasseDelete, self).get_object(queryset)
        if not self.request.user.genitore.is_rappresentante(classe):
            raise PermissionDenied
        return classe


@genitore_required
@ajax_required
def ajax_mostra_figlio_form(request):
    if request.method == "GET":
        form = AlunnoForm()
        return render(request, "genitori/figlio_form.html", {"form": form})


class AggiungiFiglio(GenitoreRequiredMixin, FormView):
    form_class = AlunnoForm
    template_name = "genitori/aggiungi_figlio.html"

    def form_valid(self, form):
        with transaction.atomic():
            alunno = form.save()
            request.user.genitore.figli.add(alunno)
        return redirect("/")


class AggiungiFiglio(GenitoreRequiredMixin, views.View):
    def get(self, request):
        form = AlunnoForm()
        return render(request, "genitori/aggiungi_figlio.html", {"form": form})

    def post(self, request):
        form = AlunnoForm(request.POST)
        if form.is_valid():
            with transaction.atomic():
                alunno = form.save()
                request.user.genitore.figli.add(alunno)
            return redirect("/")
        else:
            return render(request, "genitori/aggiungi_figlio.html", {"form": form})


class EventoCreate(GenitoreRequiredMixin, CreateView):
    template_name = "genitori/evento_create.html"
    model = Evento
    form_class = EventoForm

    def dispatch(self, request, *args, **kwargs):
        self.classe = get_object_or_404(Classe, pk=self.kwargs.get("classe_pk", None))
        return super().dispatch(request, *args, **kwargs)

    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        form.fields["invitati"].queryset = Genitore.objects.filter(
            figli__classe=self.classe
        ).exclude(user=self.request.user)
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["classe"] = self.classe
        return context

    def form_valid(self, form):
        genitore = self.request.user.genitore
        with transaction.atomic():
            evento = form.save(commit=False)
            evento.classe = self.classe
            evento.creatore = genitore
            evento.save()
            form.save_m2m()
            evento.invitati.add(genitore, through_defaults={"conferma": True})
            evento.save()

        return redirect(reverse("dettagli-classe", kwargs={"pk": self.classe.pk}))


class EventoDetail(GenitoreRequiredMixin, DetailView):
    template_name = "genitori/evento_dettagli.html"
    model = Evento
    context_object_name = "evento"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        evento = self.get_object()
        context["inviti"] = list(
            zip_longest(
                InvitoEvento.objects.all()
                .filter(evento=evento)
                .order_by("genitore_id"),
                InvitoColletta.objects.all()
                .filter(colletta__evento=evento)
                .order_by("genitore_id"),
            )
        )
        genitore = self.request.user.genitore
        context["invito_evento"] = evento.inviti.get(genitore=genitore)
        if hasattr(evento, "colletta"):
            context["invito_colletta"] = evento.colletta.inviti.all().get(
                genitore=genitore
            )
        return context


class EventoUpdate(GenitoreRequiredMixin, UpdateView):
    model = Evento
    template_name = "genitori/evento_update.html"
    context_object_name = "evento"
    fields = ("tipo", "nome", "descrizione", "data", "luogo_str")

    def get_object(self, queryset=None):
        evento = super().get_object(queryset)
        if not evento.creatore == self.request.user.genitore:
            raise PermissionDenied
        return evento


class EventoInvitoUpdate(GenitoreRequiredMixin, AjaxableResponseMixin, UpdateView):
    """
    View da usare come ajax per mostrare un form di aggiunta invitati.
    """

    model = Evento
    fields = ["invitati"]
    context_object_name = "evento"

    def get_object(self, queryset=None):
        evento = super().get_object(queryset)
        if not evento.creatore == self.request.user.genitore:
            raise PermissionDenied
        return evento

    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        invitati = form.fields["invitati"]

app/genitori/templates/genitori/aggiungi_figlio.html
<!-- vim: syntax=htmldjango
-->
{% extends 'genitori/home_genitore.html' %}

{% block genitore_content %}
<div class='row'>
    <div class='col'>
        {% include 'genitori/figlio_form.html' %}
    </div>
</div>
{% endblock genitore_content %}

app/genitori/templates/genitori/bottoni_colletta.html
<div id='invito-colletta-bottoni-wrapper'>
    <p>
    {% if invito.conferma %}
    <a onclick='accettaInvitoColletta(event)' 
       data-invitoId="{{invito.colletta.pk}}"
       href='{% url "genitori:conferma-invito-colletta" invito.pk "n" %}' 
       class='btn btn-invito btn-outline-success'>
            Parteciperai alla colletta
    </a>
    {% else %}
    <a onclick='accettaInvitoColletta(event)' 
       data-invitoId="{{invito.colletta.pk}}"
       href='{% url "genitori:conferma-invito-colletta" invito.pk "y" %}' 
       class='btn btn-primary btn-invito'>
            Conferma Partecipazione Alla Colletta
    </a>
    {% endif %}
    </p>
</div>

{% comment %}
vim: ft=htmldjango
{% endcomment %}

app/genitori/templates/genitori/bottoni_evento.html
<p>
{% if invito.conferma %}
    <a onclick='accettaInvitoEvento(event)' 
       data-eventoId="{{invito.evento.pk}}"
       href='{% url "genitori:conferma-invito-evento" invito.pk "n" %}' 
       class='btn btn-invito btn-outline-success'>
            Parteciperai all'evento
    </a>
{% else %}
    <a onclick='accettaInvitoEvento(event)' 
       data-eventoId="{{invito.evento.pk}}"
       href='{% url "genitori:conferma-invito-evento" invito.pk "y" %}' 
       class='btn btn-primary btn-invito'>
            Partecipa
    </a>
{% endif %}
{% if not no_detail_btn %}
    <a  id='evento-detail-button' 
        href='{% url "genitori:dettagli-evento" invito.evento.pk %}' 
        class='btn btn-secondary'>
        Dettagli
    </a>
{% endif %}
</p>
{% comment %}
vim: ft=htmldjango
{% endcomment %}

app/genitori/templates/genitori/classe_create.html
{% extends 'core/base.html' %}

{% block content %}

<div class="row">
    <div class='col'>
		{% include "genitori/classe_form.html" %}
	</div>
</div>

{% endblock content %}

app/genitori/templates/genitori/classe_delete.html
{% extends 'core/base.html' %}

{% block content %}

<div class='row'>
    <div class='col'>
        <h5> Vuoi veramente eliminare la classe {{classe}}? </h5>
        <form method=POST>{% csrf_token %}
            <input type=submit class='btn btn-outline-danger' 
                   value="Si, sono sicuro di volerla eliminare" />
        </form>
    </div>
</div>

{% endblock content %}

app/genitori/templates/genitori/classe_update.html
{% extends 'core/form_base.html' %}

{% block form_title %}
Aggiungi/rimuovi rappresentanti dalla classe {{classe}}
{% endblock form_title %}

{% block form_description %}
<p>
    Nota: il tuo nome non e' presente nella lista per prevenire che tu possa accidentalmente 
    escluderti dalla rappresentanza di questa classe.
</p>
{% endblock form_description %}

app/genitori/templates/genitori/colletta_create.html
{% extends "core/form_base.html" %}

{% block form_title %}
    Aggiungi una raccolta fondi per 
    {% if nome_evento %} l'evento  "{{nome_evento}}" 
    {% else %} un evento 
    {% endif %}
{% endblock form_title %}

{% block form_description %}
<p>
    Puoi associare una raccolta fondi ad un evento.
</p>
{% endblock form_description %}

{% block submit_text %}
    Aggiungi
{% endblock submit_text %}

app/genitori/templates/genitori/colletta_detail.html
{% extends 'core/base.html' %}

{% block content %}

{% include "genitori/colletta_detail_frame.html" %}

{% endblock content %}

app/genitori/templates/genitori/conferma_invito.html
{% extends 'core/base.html' %}

{% block content %}
{% load crispy_forms_tags %}

<div class='row'>
    <div class='col'>
        <h1> Benvenuto {{user.full_name}} </h1>
        <h3> 
            Sembra che tu sia stato invitato a far parte del gruppo della {{classe}} 
        </h3>
        <p> Se vuoi unirti a questa classe, usa il pulsante qui sotto. </p>
        <div style='padding:1pt'>
            <form method='post' action="#">
                {% csrf_token %}
                <button onclick="mostraFiglioForm(event)" class='btn btn-primary btn-large'>
                    Sono il genitore di un bambino di questa classe
                </button>
                <hr />
                <div id='wrapper-figli' style='display:none' class='row'>
                    <h3> Specifica il figlio che fa parte di questa classe </h3>
                    <div class='col-6'>
                        <h5> Se gia' lo hai registrato, scegli un figlio da qui </h5>
                        {{form_scelta_figlio|crispy}}
                    </div>
                    <div class='col-6'>
                        <h5>Altrimenti, aggiungine uno ora</h5>
                        {{form_figlio|crispy}}
                    </div>
                    <button type='submit' class='btn btn-primary'>
                        Conferma
                    </button>
                </div>
            </form>
        </div>
    <script>
        function mostraFiglioForm(e) {
            e.preventDefault()
            document.getElementById('wrapper-figli').style.display = '';
            return false;
        }
    </script>
    </div>
</div>

{% endblock content %}

app/genitori/templates/genitori/evento_update.html
{% extends "core/form_base.html" %}

{% block form_title %}
Modifica evento {{evento}}
{% endblock form_title %}

{% block submit_text %}
Conferma modifiche
{% endblock submit_text %}

app/genitori/templates/genitori/home_genitore.html
{% extends "core/base.html" %}

{% block content %}

<div class='row'>
    <div class='col'>
        <h1> 
            Ciao 
            <a href="{% url 'genitori:home-genitore' %}">
                {{user.full_name}}
            </a>
        </h1>
		<p> <a href="{% url 'modifica-profilo' %}"> 
			Impostazioni Profilo 
		</a> </p>
    </div>
</div>
<hr />

{% block genitore_content %}

	{% include "genitori/pannello_figli.html" %}

	{% include "genitori/pannello_classi.html" %}

{% endblock genitore_content %}

{% endblock content %}

app/genitori/templates/genitori/login_genitore.html
<!-- 
    vim: syntax=htmldjango  
-->
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class='row'>
    <h1> Accedi come genitore </h1>
</div>
<hr />

<div class='row'>

    <form method='post' action="{% url 'genitori:login-genitore' %}">
            {{ form|crispy }}
            {% csrf_token %}
        <input type='submit' class='btn btn-primary' value='Accedi' />
    </form>

</div>
{% endblock content %}

app/genitori/templates/genitori/pannello_figli.html
<!-- vim: syntax=htmldjango
-->
<div class='row'>
    <div class='col'>
		<div style='display:flex;'>
			<h2 style='flex:10;'> 
				Figli 
			</h2>
		</div>
		<div id='figlio-form' class='row'></div>
	</div>
</div>


<div class='row'>

        {% for figlio in user.genitore.figli.all %}
            <div class='col-5'>
                <h5>
                    <a href='{% url "dettagli-classe" figlio.classe.pk %}'>
                        {{ figlio.nome|title }} {{ figlio.cognome|title }}
                    </a>
                </h5>
                <p> Classe: {{figlio.classe}} {{ figlio.scuola|title }}</p>
                <hr/>
            </div>
        {% empty %}

        <div class='col'>
            <p> Sembra che tu non abbia aggiunto figli che vanno a scuola. </p>
        </div>

        {% endfor %}

</div>

app/genitori/templates/genitori/signup_genitore.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class='row' >
    <div class='col-6' >
        <h1> Registrazione genitore </h1>
    </div>
</div>
<div class='row' >
    <div class='col-6' >
        <form method=POST action='{% url "genitori:signup-genitore" %}'>
				{% csrf_token %}
                {{ form|crispy }} 
            <input type='submit' value='submit' class='btn btn-primary' />
        </form>
    </div>
</div>

    <script>
        $( function() { 
            $('[data-target="#data-nascita-picker"]').datepicker({
                yearRange: '1920:2001',
                changeMonth: true,
                changeYear: true
            }); 
            $('[data-target="#data-nascita-picker"]').attr('autocomplete','off'); 
        } );
    </script>
{% endblock content %}