app/ClasseApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core.views import *
from api.urls import router

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path(
        "insegnanti/",
        include(("insegnanti.urls", "insegnanti"), namespace="insegnanti"),
    ),
    path("genitori/", include(("genitori.urls", "genitori"), namespace="genitori")),
    # path("api/", include(router.urls)),
    # path('accounts/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

app/api/urls.py
from django.urls import path, include
from rest_framework import routers
from .viewsets import *

router = routers.DefaultRouter()
router.register("evento", EventoViewSet)
router.register("compito", CompitoViewSet)
router.register("classe", ClasseViewSet)
router.register("alunno", AlunnoViewSet)
router.register("genitore", GenitoreViewSet)
router.register("insegnante", InsegnanteViewSet)
router.register("user", UserViewSet)
# router.register(r'users', UserViewSet)
urlpatterns = router.urls

urlpatterns += [path("rest-auth/", include("rest_auth.urls"))]

app/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *
from api import urls as api_urls

urlpatterns = [
    path("", home_view, name="home"),
    path("logout/", logout, name="logout"),
    path("profile/edit", UserUpdateView.as_view(), name="modifica-profilo"),
    path("classe/<uuid:uuid>/", invito_classe, name="invito-classe"),
    path("classe/trova/", ricerca_classe, name="ricerca-classe"),
    path("classe/<int:pk>/", ClasseDetail.as_view(), name="dettagli-classe"),
    path(
        "password/",
        auth_views.PasswordChangeView.as_view(
            template_name="core/password_change.html", success_url="/"
        ),
        name="dettagli-classe",
    ),
]

app/genitori/urls.py
from django.urls import path
from .views import *
from core.views import home_view

urlpatterns = [
    path("signup/genitore/", SignupGenitore.as_view(), name="signup-genitore"),
    path("login/genitore/", LoginGenitore.as_view(), name="login-genitore"),
    path("profile/genitore/", home_view, name="home-genitore"),
    path("classe/create", ClasseCreate.as_view(), name="aggiungi-classe"),
    path("classe/<int:pk>/delete", ClasseDelete.as_view(), name="classe-delete"),
    path(
        "classe/<uuid:uuid>/conferma-genitore",
        ClasseAggiungiGenitore.as_view(),
        name="classe_aggiungi_genitore",
    ),
    path(
        "classe/<int:pk>/modifica_rappresentanti",
        ModificaRappresentanti.as_view(),
        name="modifica_rappresentanti",
    ),
    # eventi
    path(
        "genitore/classe/<int:classe_pk>/aggiungi-evento",
        EventoCreate.as_view(),
        name="aggiungi-evento",
    ),
    path("evento/<int:pk>/", EventoDetail.as_view(), name="dettagli-evento"),
    path("evento/<int:pk>/update", EventoUpdate.as_view(), name="evento-update"),
    # inviti a eventi
    path(
        "evento/<int:pk>/inviti_edit",
        EventoInvitoUpdate.as_view(template_name="genitori/evento_invito_form.html"),
        name="aggiungi-invito-evento",
    ),
    path(
        "invito_evento/<int:pk>/<str:accetta>/",
        ajax_accetta_rifiuta_invito_evento,
        name="conferma-invito-evento",
    ),
    # collette
    # path("colletta/create", CollettaCreate.as_view(), name="colletta-create"),
    path(
        "evento/<int:evento_pk>/colletta/create",
        CollettaAssociate.as_view(),
        name="colletta-evento-associa",
    ),
    path(
        "evento/<int:pk>/colletta/update",
        CollettaUpdate.as_view(),
        name="colletta-update",
    ),
    # path("colletta/<int:pk>", CollettaDetail.as_view(), name="colletta-detail"),
    path(
        "invito_colletta/<int:pk>/<str:accetta>/",
        ajax_accetta_rifiuta_invito_colletta,
        name="conferma-invito-colletta",
    ),
]

app/insegnanti/urls.py
from django.urls import path
from .views import (
    SignupInsegnante,
    LoginInsegnante,
    ClasseCreate,
    ajax_mostra_compito_form,
    AggiungiCompito,
    ClasseAggiungiInsegnante,
)
from core.views import home_view

urlpatterns = [
    path("signup/insegnante/", SignupInsegnante.as_view(), name="signup-insegnante"),
    path("login/insegnante/", LoginInsegnante.as_view(), name="login-insegnante"),
    path("home/insegnante/", home_view, name="home-insegnante"),
    path("classe/create", ClasseCreate.as_view(), name="aggiungi-classe"),
    path(
        "insegnante/classe/<int:classe_pk>/aggiungi-compito/",
        AggiungiCompito.as_view(),
        name="aggiungi-compito",
    ),
    path(
        "classe/<uuid:uuid>/conferma-insegnante",
        ClasseAggiungiInsegnante.as_view(),
        name="classe_aggiungi_insegnante",
    ),
    path(
        "ajax/forms/classe/<int:classe_pk>/aggiungicompito/",
        ajax_mostra_compito_form,
        name="ajax-compito-form",
    ),
]

app/core/forms.py
from django import forms
from django.contrib.auth.forms import (
    UserCreationForm,
    UserChangeForm,
    AuthenticationForm,
)
from django.db import transaction

from .models import User, Insegnante, Genitore

# Form che riguardano solo autenticazione utenti (istanze di User)


class AuthenticationFormInsegnante(AuthenticationForm):
    def confirm_login_allowed(self, user):
        if not hasattr(user, "insegnante"):
            raise forms.ValidationError(
                "Questo account non appartiene ad un insegnante", code=""
            )


class AuthenticationFormGenitore(AuthenticationForm):
    def confirm_login_allowed(self, user):
        if not hasattr(user, "genitore"):
            raise forms.ValidationError(
                "Questo account non appartiene ad un genitore", code=""
            )


class CustomUserCreationForm(UserCreationForm):
    data_nascita = forms.DateTimeField(
        input_formats=["%m/%d/%Y"],
        widget=forms.DateInput(
            attrs={
                "class": "form-control datetimepicker-input",
                "data-target": "#data-nascita-picker",
            }
        ),
    )

    class Meta:
        model = User
        fields = ("email", "first_name", "last_name", "data_nascita")


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("email", "first_name", "last_name", "data_nascita")


class UuidForm(forms.Form):
    """ Form che rappresenta un singolo UUID inserito da un utente per ricercare una classe
    """

    uuid = forms.UUIDField(label="Codice di invito alla classe", required=True)

app/core/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import (
    CreateView,
    FormView,
    RedirectView,
    DetailView,
    UpdateView,
)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse
from .models import *
from .forms import UuidForm, CustomUserChangeForm

# Create your views here.


def is_genitore(user):
    return hasattr(user, "genitore")


def is_insegnante(user):
    return hasattr(user, "insegnante")


class QualcunoRequiredMixin(LoginRequiredMixin, UserPassesTestMixin):

    login_url = "/"

    def test_func(self):
        user = self.request.user
        return is_genitore(user) or is_insegnante(user)


def home_view(request):
    if request.user.is_authenticated:
        form_ricerca_classe = UuidForm()
        context = {"form_ricerca_classe": form_ricerca_classe}
        if is_insegnante(request.user):
            return render(request, "insegnanti/home_insegnante.html", context=context)
        if is_genitore(request.user):
            return render(request, "genitori/home_genitore.html", context=context)
    return render(request, "core/home.html")


def logout(request):
    auth.logout(request)
    return redirect("/")


class LogoutView(RedirectView):
    """
    Provides users the ability to logout
    """

    url = "/"

    def get(self, request, *args, **kwargs):
        auth.logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = CustomUserChangeForm
    template_name = "core/user_update.html"
    success_url = "/"

    def get_object(self, queryset=None):
        return self.request.user


@login_required
def invito_classe(request, uuid):
    user = request.user
    classe = get_object_or_404(Classe, uuid=uuid)
    if is_insegnante(user):
        return redirect(
            reverse("insegnanti:classe_aggiungi_insegnante", kwargs={"uuid": str(uuid)})
        )
    elif is_genitore(user):
        return redirect(
            reverse("genitori:classe_aggiungi_genitore", kwargs={"uuid": str(uuid)})
        )
    else:
        raise PermissionDenied


@login_required
def ricerca_classe(request):
    if request.method == "POST":
        uuid_form = UuidForm(request.POST)
        if uuid_form.is_valid():
            uuid = uuid_form.cleaned_data["uuid"]
            classe = get_object_or_404(Classe, uuid=uuid)
            return invito_classe(request, uuid)
    return redirect("/")


class ClasseDetail(QualcunoRequiredMixin, DetailView):
    """ View unica per permettere la get_absolute_url sul modello Classe
    """

    template_name = "core/classe_dettagli.html"
    model = Classe
    context_object_name = "classe"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        oggi = timezone.now()
        classe = context["classe"]
        compiti = classe.compiti.all()
        context["compiti"] = compiti.filter(data__gte=oggi)
        context["compiti_passati"] = compiti.filter(data__lte=oggi)

        # creazione link invito alla classe
        classe_uuid = context["classe"].uuid
        invito_url = "{}://{}{}".format(
            self.request.scheme,
            self.request.get_host(),
            reverse("invito-classe", args=(classe_uuid,)),
        )
        context["invito_url"] = invito_url

        if is_genitore(self.request.user):
            # eventi = classe.eventi.all()
            inviti = self.request.user.genitore.inviti.all().filter(
                evento__classe=classe
            )
            # lista di tuple con evento e invito associato
            context["eventi_inviti"] = zip((invito.evento for invito in inviti), inviti)

        return context

app/core/templates/core/base.html
<!--
    vim: syntax=htmldjango:
-->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title></title>

  <link rel="stylesheet" href="/static/style.css">

<!-- jquery -->
<script src="http://code.jquery.com/jquery-3.4.1.min.js" crossorigin='anonymous'></script>
<script src="http://code.jquery.com/ui/1.12.1/jquery-ui.min.js" crossorigin='anonymous'></script>
<link rel='stylesheet' href="http://code.jquery.com/ui/1.12.1/themes/cupertino/jquery-ui.css" crossorigin=anonymous>

  <!-- Bootstrap CSS from CDN -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- OpenIconic Icon Font -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" integrity="sha256-BJ/G+e+y7bQdrYkS2RBTyNfBHpA9IuGaPmf9htub5MQ=" crossorigin="anonymous" />
</head>

<body>

	{% block navbar %}
		{% include "core/navbar.html" %}
	{% endblock navbar %}

    <div class='container'>
        {% block content %}
        {% endblock content %}
    </div>

</body>
</html>

app/core/templates/core/classe_create.html
{% extends 'core/base.html' %}

{% block content %}

{% with alunni_form as formset %}
{% include 'core/formset.html' %}
{% endwith %}

{% endblock content %}

app/core/templates/core/classe_dettagli.html
{% if user.genitore %}
{% include "genitori/classe_dettagli.html" %}
{% else %}
{% include "insegnanti/classe_dettagli.html" %}
{% endif %}

app/core/templates/core/classe_titolo.html
<h1> Classe {{ classe }} 

</h1>
<p>
    {% if user.insegnante %}
        <button class='btn btn-primary' id='aggiungi-compito'>
                Aggiungi compiti
        </button> 
    {% endif %}
    {% if is_rappresentante %}
        <button href='{% url "genitori:classe-delete" classe.pk %}' 
           class='btn btn-outline-danger'>
            Elimina classe
        </button>
    {% endif %}
    <button onclick='mostraInviti(event)' type=button class='btn btn-primary'> 
        Mostra link d'invito
    </button> 
</p>
<div id='inviti-wrapper' style='display:none'>
    <p>
        Il codice di invito e' <code>{{classe.uuid}}</code>
    </p>
    <p> Copia questo link e invialo a chi vuoi invitare: 
        <input value='{{invito_url}}' type=text id='invito-url' readonly />
        <button class='btn btn-primary' onclick='copiaTesto(event)'>
            Copia Link
        </button>
    </p>
</div>
<script>
    function mostraInviti(e) {
        $('#inviti-wrapper').slideDown();
        return false;
    }
    function copiaTesto(e) {
        var testo = document.getElementById('invito-url');
        testo.select();
        document.execCommand('copy');
    }
</script>
{% comment %}
vim: ft=htmldjango
{% endcomment %}

app/core/templates/core/compiti_lista.html
{% comment %}
    vim: ft=htmldjango:
{% endcomment %}

<div class='row'>
        <div class='col-12'>
            <h2> Prossimi compiti </h2>
        </div>
        {% for compito in compiti %}
                {% include 'core/scheda_compito.html' %}
        {% empty %}
        <div class='col-12'>
            <p> Nulla! </p>
        </div>
        {% endfor %}
</div>

<div class='row' style='background: #eee;margin-top:2rem;'>
    <div class='col-12' >
        <div class=row id='mostra-compiti-passati'>
            <div class=col-10>
                <h2> Compiti passati </h2>
                <p>
                <small id='smalltext'> (clicca per espandere) </small> 
                </p>
            </div>
        </div>
        <div id='lista-compiti-wrapper' style='display:none'>
            <div class='row'>
            {% for compito in compiti_passati %}
                {% include 'core/scheda_compito.html' %}
            {% empty %}
                <p> Nulla! </p>
            {% endfor %}
            </div>
        </div>
    </div>
</div>
    <script>
        $('#mostra-compiti-passati').click(function(e) {
            $('#lista-compiti-wrapper').slideToggle();
            $('#smalltext').toggle();
        });
    </script>

app/core/templates/core/conferma_invito.html
{% extends 'core/base.html' %}

{% block content %}
{% load crispy_forms_tags %}

<div class='row'>
    <div class='col'>
        <h1> Benvenuto {{user.full_name}} </h1>
        <h3> 
            Sembra che tu sia stato invitato a far parte del gruppo della {{classe}} 
        </h3>
        <p> Se vuoi unirti a questa classe, usa il pulsante qui sotto. </p>
        {% if insegnanti_url %}
        <div style='padding:1pt'>
            <form 
                method=post
                action="#">
                {% csrf_token %}
                <button type=Submit class='btn btn-primary btn-large'>
                    Sono un'insegnante di questa classe
                </button>
            </form>
        </div>
        {% endif %}
        {% if genitori_url %}
        <div style='padding:1pt'>
            <form method='post' action="#">
                {% csrf_token %}
                <button onclick="mostraFiglioForm(event)" class='btn btn-primary btn-large'>
                    Sono il genitore di un bambino di questa classe
                </button>
                <hr />
                <div id='wrapper-figli' style='display:none' class='row'>
                    <h3> Specifica il figlio che fa parte di questa classe </h3>
                    <div class='col-6'>
                        <h5> Se gia' lo hai registrato, scegli un figlio da qui </h5>
                        {{form_scelta_figlio|crispy}}
                    </div>
                    <div class='col-6'>
                        <h5>Altrimenti, aggiungine uno ora</h5>
                        {{form_figlio|crispy}}
                    </div>
                    <button type='submit' class='btn btn-primary'>
                        Conferma
                    </button>
                </div>
            </form>
        </div>
    <script>
        function mostraFiglioForm(e) {
            e.preventDefault()
            document.getElementById('wrapper-figli').style.display = '';
            return false;
        }
    </script>
        {% endif %}
    </div>
</div>

{% endblock content %}

app/core/templates/core/form_base.html
{% extends "core/base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<div class='row'>
</div>

<div class='row justify-content-center'>
    <div class='col'>
        <h2> 
            {% block form_title %}{% endblock form_title %}
        </h2>
        {% block form_description %}
        {% endblock form_description %}
    </div>
    <div class='col-7'>
        <form method=post>{% csrf_token %}
            {{form|crispy}}
            <input type=submit value="{% block submit_text %}Conferma{% endblock submit_text %}" class='btn btn-primary' />
        </form>
    </div>
</div>

{% endblock content %}

app/core/templates/core/form_invito_classe.html
{% load crispy_forms_tags %}
<div class='col'>
    <h3> Inserisci il codice invito di una classe </h3>
    <p> <small> 
        Ottieni il codice invito da un altro genitore della tua classe 
    </small></p>
    <form action="{% url 'ricerca-classe' %}" method=POST>{% csrf_token %}
        {{form_ricerca_classe|crispy}}
        <input value='Cerca' id='cerca-classe-submit' type=submit class='btn btn-primary' />
    </form>
</div>

app/core/templates/core/formset.html
{% comment %}
 vim: ft=htmldjango: 
{% endcomment %}
<form method="post">
    {{ formset.management_form }}
    <table>
        {% for form in formset %}
        {{ form }}
        {% endfor %}
    </table>
</form>

app/core/templates/core/home.html
{% extends "core/base.html" %}

{% block content %}

{% if not user.is_authenticated %}

<div class='row'>
	<div class='col-12'>
		<h1> Benvenuto </h1>
	</div>
</div>

<div class='row'>
	<div class='col-12'>

		<h3> Registrati come genitore </h3>

		<p> 
			Registrandoti in questa maniera, potrai creare una classe e invitare 
			gli altri genitori della tua classe 
		</p>
		<a class='btn btn-primary' href="{% url 'genitori:signup-genitore' %}">
			Registrati come genitore
		</a>

	</div>
</div>


<div class='row'>
	<div class='col-12'>

		<h3> Registrati come insegnante </h3>
		<p> 
			Registrandoti in questa maniera, potrai creare una classe e invitare 
			gli altri insegnanti della tua classe 
		</p>
		<a class='btn btn-primary' href="{% url 'insegnanti:signup-insegnante' %}">
            Registrati come insegnante
		</a>
	</div>
</div>


<div class='row'>
	<div class='col-12'>
		<h3> Accedi come: </h3>
		<div class='flexer' >
			<a style='flex:0' class='btn btn-primary' href="{% url 'genitori:login-genitore' %}">
                Genitore
			</a>
			<a style='flex:0' class='btn btn-primary' href="{% url 'insegnanti:login-insegnante' %}">
                Insegnante
			</a>
		</div>
	</div>
</div>

{% elif user.is_superuser %}
<h1> che ci fai tu qui? </h1>
{% else %}
<h1> Benvenuto {{user.first_name}} {{user.last_name}} </h1>
{% endif %}

{% endblock content %}

app/core/templates/core/navbar.html
<!-- vim: syntax=htmldjango 
-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	<ul class="navbar-nav mr-auto">
	  <li class="nav-item active">
		<a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
	  </li>
	  <li class="nav-item">
		  <a class="nav-link" href=""></a>
	  </li>
	  {% if user.is_authenticated %}

      <!-- Se l'utente c'e', mostra solo pulsante logout -->
	  <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
	  </li>
      
	  {% else %}

	  <!-- Registrazione (dropdown) -->
	  <li class="nav-item dropdown">
		<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		  Registrazione
		</a>
		<div class="dropdown-menu" aria-labelledby="navbarDropdown">
		  <a class="dropdown-item" href="{% url 'insegnanti:signup-insegnante' %}">
			  Come Insegnante
		  </a>
          <a class="dropdown-item" href="{% url 'genitori:signup-genitore' %}">Come Genitore</a>
		</div>
	  </li>
	  <!-- Login (dropdown) -->
	  <li class="nav-item dropdown">
		<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		  Accedi
		</a>
		<div class="dropdown-menu" aria-labelledby="navbarDropdown">
		  <a class="dropdown-item" href="{% url 'insegnanti:login-insegnante' %}">
			  Come Insegnante
		  </a>
		  <a class="dropdown-item" href="{% url 'genitori:login-genitore' %}">Come Genitore</a>
		</div>
	  </li>

	  {% endif %}

	</ul>
    {% comment %}
	<form class="form-inline my-2 my-lg-0">
	  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
	  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Cerca</button>
	</form>
    {% endcomment %}
  </div>
  {{user.full_name|title}}
</nav>

app/core/templates/core/password_change.html
{% extends "core/form_base.html" %}

{% block form_title %}
Cambia la tua password
{% endblock form_title %}

app/core/templates/core/scheda_compito.html
{% comment%}
    vim: syntax=htmldjango
    
    Si aspetta di ricevere un oggetto di nome 'compito' nel contesto
{% endcomment %}

<div class='col-6 card' style='padding:0; margin: 4px 0;'>
    <h5 class='card-header'> 
        Materia: {{compito.materia|title}} 
    </h5>
    {% if compito.foto %}
    <div class='card-img-top'>
        <a 
         href='{{ compito.foto.url }}' >
        <img
            style='max-height:200px;display:block;margin:auto;max-width:100%; height: auto;'
            src='{{ compito.foto.url }}' 
            style='' />
        </a>
    </div>
    {% endif %}
    <div class='card-body'>
        <p class='card-text'> 
            Entro il: {{ compito.data }} 
            <br />
            <small> Assegnato da: {{compito.creatore.full_name}} </small>
        </p>
        <p class='card-text'>
            {{compito.testo}}
        </p>
    </div>
</div>

app/core/templates/core/user_update.html
{% extends "core/form_base.html" %}

{% block form_title %}
Modifica il tuo profilo
{% endblock form_title %}